services:
  front:
    container_name: vital-image
    image: vinicosta37/vital-image:1.0
    volumes:
      - vital-volume:/var/www/html

  nginx:
    container_name: vital-nginx
    image: vinicosta37/vital-image-nginx:latest
    depends_on:
      - front
    volumes:
      - vital-volume:/var/www/html
    ports:
      - 80:80

volumes:
  vital-volume: